### ISSUE TITLE
ValueError: malformed node or string: <_ast.Name object at 0x7f8da4cda160>

### ISSUE THREAD

**Issue by GabrielLin** [Liu-Hy/nlp-contrib-graph#12]
When I ran `C.py` in the `train_rel` folder, the following errors were shown, could you please help?

```
Traceback (most recent call last):
  File "C.py", line 62, in <module>
    train_df = convert(t_df, 0)
  File "C.py", line 48, in convert
    trip_ls = load(arr[i, 7])
  File "/home/XXX/miniconda3/envs/py36liuhy/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/home/XXX/miniconda3/envs/py36liuhy/lib/python3.6/ast.py", line 77, in _convert
    left = _convert(node.left)
  File "/home/XXX/miniconda3/envs/py36liuhy/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Name object at 0x7f8da4cda160>

```

**Comment by Liu-Hy** [comment]
The problem is caused by a strange line in <code>interim/triples.csv</code>. I ran <code>ext.py</code> again to update this file, and then the script can run. It was really strange. Thanks for reporting.

**Comment by GabrielLin** [comment]
The issue has been fixed. Thank you.
